### ISSUE TITLE
New feature suggestion: More flexibility on Message/Mention Notifications

### ISSUE THREAD

**Issue by heldheld** [811Alex/NotifMod#12]
This mod is a great idea!

I'd love some more flexibility with the message- and mention notifications, just the sound alone is not really enough for me to grab my attention when playing on a busy multiplayer server. Also, trying to find the message in a busy chat could be made a little easier.

Maybe the ability to change the colour or fontstyle (bold/italic/underlined) of the word/username that's mentioned in the chat message that was sent, and changing the message type (extra chat message/actionbar/title/subtitle) like what is possible with the Equipment Durability Notifications could make this mod even better.

**Comment by 811Alex** [comment]
Added the ability to change the colour or fontstyle (bold/italic/underlined), when notified, using a separate RegEx pattern.
I didn't add the ability to change the message type, 'cause I don't think it really fits the chat.
I did however take advantage of the indicator next to messages, that newer MC versions now have, to be able to distinguish between messages that gave you a notification, by adding the ability to color it.

Hopefully that will suit your needs. Feedback is always welcome.
