### ISSUE TITLE
crash when i click the + in mod config

### ISSUE THREAD

**Issue by killerkong24** [811Alex/NotifMod#14]
![image](https://user-images.githubusercontent.com/109182281/210120364-69172c6d-dcb2-465b-9c1a-40ed65874e0f.png)

i was trying change the sounds for the mod but it send the error message 
The game crashed whilst mouseclicked event handler
Error: java.lang.NoSuchFieldError: field_15015
error code -1

**Comment by 811Alex** [comment]
Can't reproduce, versions (mc, notifmod & dependencies)?

**Comment by killerkong24** [comment]
mc: fabric 1.19.3, notifmod 1.3.4, fabric api 0.70, cloth-config: 9.0.93, modmenu: 5.02

**Comment by 811Alex** [comment]
Alright, pretty sure it's a Cloth Config API issue, but updating to 9.0.94 seems to fix it, so just do that and it should work! :)
