### ISSUE TITLE
Configuration button missing

### ISSUE THREAD

**Issue by bburrgg** [811Alex/NotifMod#15]
I am using NotifMod version 1.16.5 and the configuration button in Mod Menu is not popping up. Am I in the right spot to configure? Is the mod broken for me? Also, it does say that Mod Menu is optional which confuses me because I have no idea where I would pull up the configuration menu other then the "Mods" tab. The mod works but I haven't figured out how to configure it yet. I have never used Mod Menu so sorry if the solution is very obvious. (I have tried launching the mod with only the 3 required mods too, but the button is still missing)
![image](https://user-images.githubusercontent.com/122055236/210875807-f8480f94-3c63-4fcf-bd35-3c039b3149ee.png)

**Comment by 811Alex** [comment]
You're in the right spot, this is most likely the same as #8 
Unfortunately, there are currently no plans to backport the fix to older MC versions, unless heavily requested.
However, you can just use an older version of Cloth Config API (4.14.64 seems to work for MC 1.16.5) and it should work fine!

BTW, Mod Menu being optional, in this case, just means that the mod will load fine without it and that you can change the config by editing the config file manually. I recommend using Mod Menu though.

**Comment by 811Alex** [comment]
Oh also, if I remember correctly, the rest of the mod should still work fine, so if you're forced to use a newer version of Cloth Config for the other mods, you could try doing that, after configuring it with the older version (or manually editing the file, as mentioned).
