### ISSUE TITLE
i don't get it

### ISSUE THREAD

**Issue by carmeops** [811Alex/NotifMod#20]
i don't get it

i tested with RegExr and it worked fine, but ingame it's different
i set this filter:
.*(?<!~Carmeops.*)(carm).*

so it should notify me for every mention of carm, except when it's me talking, (the server where i am show my chat messages as:
~Carmeops >

and when i do:
~Carmeops > carm

indeed, no notification happen, however, i discovered that if i say instead:
~Carmeops > "carm"

with the quotation marks, then suddenly i get notified!
why? i don't get it

**Comment by 811Alex** [comment]
The mod already filters out outgoing messages, so you shouldn't get notifs for things you send.
If you want notifications when someone mentions carm, `.*(carm).*` should do fine.

If you really need to do negation, perhaps a negative lookahead would do it `(?!~Carmeops).*(carm).*` (haven't tested this one and it could be better).

**Comment by 811Alex** [comment]
Closing, but feel free to let me know if you're still having issues.
