### ISSUE TITLE
i dont know how to configure the mention notification

### ISSUE THREAD

**Issue by peow** [811Alex/NotifMod#23]
I followed the tutorial on the mod page on Modrinth
![image](https://github.com/811Alex/NotifMod/assets/105888751/967672d1-015c-4f93-81c6-4aaabd11060a)

and then in-game it looked like this:

![image](https://github.com/811Alex/NotifMod/assets/105888751/a571954f-e720-4252-b5da-4f781fb89ef9)

and and using a command block to test, it hasn't worked

![image](https://github.com/811Alex/NotifMod/assets/105888751/3a953033-f2a5-41a1-9100-1a9dd9aa112f)

i know the mod is working because when my username (peow__) is mentioned, with the default mod settings, the notification sound happens

*im using the version v1,4, the last version for fabric 1.20.1

**Comment by 811Alex** [comment]
Oh oops, Modrinth's description was missing some asterisks after those dots (may or may not be due to a recent change lol).
Thanks for reporting it, it's fixed now.
