### ISSUE TITLE
Chat notification crashes if you don't send message first

### ISSUE THREAD

**Issue by Pepsied-5229** [811Alex/NotifMod#24]
Each time I start Minecraft with NotifMod and load a singleplayer world, I have to send one chat message, or else the next text that shows in the chat will crash the game with this error.
Now granted, I have over 200 mods enabled so I'm not surprised or disappointed, but the mod that's causing crashes with NotifMod (that I can see) is [Auto Elytra](https://www.curseforge.com/minecraft/mc-mods/auto-elytra). Auto Elytra is enabled by default whenever you join a world. When I disable/enable it with the toggle keybind, it sends a chat message with its new toggle state. However, if it's the first chat message of that session, then the game crashes. And if I send a message and then toggle, it works perfectly and does not crash.
So, I'm guessing it's not just Auto Elytra, rather the crash can be triggered by anything that sends a message other than a player. But I don't have any way of testing that. I also tried to test the bug in multiplayer, but I couldn't get a chance to disable/enable it before someone or something else sent a message.
[crash-2023-12-30_13.27.20-client.txt](https://github.com/811Alex/NotifMod/files/13799170/crash-2023-12-30_13.27.20-client.txt)

**Comment by 811Alex** [comment]
Thanks for the report!
From the crash report, it _does_ look like a NotifMod issue, but I'm unable to reproduce it on my end, with NotifMod + Auto Elytra.
Could you share your NotifMod settings? Just the chat notification settings would be enough (or you can post your NotifMod config file, if you prefer).

**Comment by Pepsied-5229** [comment]
[notifmod.json](https://github.com/811Alex/NotifMod/files/13823324/notifmod.json)
Here you go. I hope this helps. ^_^

**Comment by 811Alex** [comment]
Still couldn't reproduce. Not sure what exactly would trigger it - perhaps it's some other mod combo. Either way, I patched it according to the crash log.
Test the latest version and if it still does it, let me know and I'll reopen the issue.
Happy new year!

**Comment by Pepsied-5229** [comment]
I'm sorry that you could not reproduce the bug, and you're probably right in which one or more of my 200 loaded mods would make for some buggy combination. Either way, I can say that the patch v1.5.1 has fixed the issue, and I no longer crash without first sending a message. Thank you very much, Alex.
