### ISSUE TITLE
Mention Notification Playing Whenever I Send Any Message

### ISSUE THREAD

**Issue by NerdieBirdieYT** [811Alex/NotifMod#25]
Hello! Thanks for the brilliant mod!

I am using the following Regex code: **.\*(\p|nerdiebirdie|birdie|nerdie).\*** in order to receive pings when I'm mentioned. My username is NerdieBirdieYT. Whenever I send a message, the notification sounds plays, I assume because it sees my username at the start of the message.

Is there a way to prevent this?

**Comment by 811Alex** [comment]
Normally the mod ignores your own messages.
Is this on the normal "chat" filter or did you have to use a different one due to a server-side chat plugin?

**Comment by NerdieBirdieYT** [comment]
> Normally the mod ignores your own messages. Is this on the normal "chat" filter or did you have to use a different one due to a server-side chat plugin?

It's using the "chat" filter, although I'm trying to use it on a server which has plugins.

**Comment by NerdieBirdieYT** [comment]
> Could you send me a screenshot of a chat message, or even better, a log line printed with the "Log message info" setting on?

Yes! Here's the line:
[21:38:59] [Render thread/INFO]: [NotifMod] Incoming matching message (game info, mention, case-insensitive): ? NerdieBirdieYT > test

And here's an image. I do have a symbol in front of my name due to having a rank.
https://i.imgur.com/v1duDYN.png

**Comment by 811Alex** [comment]
ok, so this one says it matched the filter for "game info" *mentions*
what do you currently have in that one? is it .\*(\p|nerdiebirdie|birdie|nerdie).\* ?

**Comment by NerdieBirdieYT** [comment]
> ok, so this one says it matched the filter for "game info" _mentions_
> what do you currently have in that one? is it .*(\p|nerdiebirdie|birdie|nerdie).* ?

.*(\p|nerdiebirdie|birdie|nerdie).*

![0jpxYcd](https://github.com/811Alex/NotifMod/assets/73838946/c9888a5e-d5fe-4103-82a2-95c6448694b3)

**Comment by 811Alex** [comment]
Yeah, so essentially, it's due to a server plugin that stylizes the chat, but as is often the case with those, it uses the "game info" channel. "game info" messages don't have you set as the sender when you send something, unlike normal chat messages, so NotifMod can't know that you were the sender and ignore outgoing messages like normal. The fix is simple, but depends on the server's custom chat format.

For your case, try this: `.+>.*(\p|nerdiebirdie|birdie|nerdie).*`
it will tell it to only notify for messages that contain your name after the ">".
Let me know if it works! :)

**Comment by NerdieBirdieYT** [comment]
> Yeah, so essentially, it's due to a server plugin that stylizes the chat, but as is often the case with those, it uses the "game info" channel. "game info" messages don't have you set as the sender when you send something, unlike normal chat messages, so NotifMod can't know that you were the sender and ignore outgoing messages like normal. The fix is simple, but depends on the server's custom chat format.
> 
> For your case, try this: `.+>.*(\p|nerdiebirdie|birdie|nerdie).*` it will tell it to only notify for messages that contain your name after the ">". Let me know if it works! :)

Works like a charm! Thanks so much!
