### ISSUE TITLE
Error spam in console

### ISSUE THREAD

**Issue by Vazgen005** [811Alex/NotifMod#3]
There's the log - https://paste.gg/p/anonymous/1b131c44435b4ccba57c9daafaaaa1a9

**Comment by 811Alex** [comment]
Seems like the only way I could reproduce this was to unbind the mod's reminder keybind. I'll look into fixing it when I get some time. In the meantime, could you confirm that the spam stops for you, if you bind a key for it?

**Comment by Vazgen005** [comment]
Yes, it fixed when i binded it.

**Comment by Vazgen005** [comment]
thx for fast answer

**Comment by 811Alex** [comment]
np, I'll keep this open for now, since it's still a bug that I need to look into
