### ISSUE TITLE
Can't hide mention notification

### ISSUE THREAD

**Issue by yunus-cakir** [811Alex/NotifMod#30]
Hi! I really like this mod but it keep showing all the time even I reply the mention :(((
![image](https://github.com/811Alex/NotifMod/assets/83448525/fa2c7cb0-f6ce-4c9e-bbc8-a4a8f2cf6954)

**Comment by 811Alex** [comment]
This doesn't seem to be from this mod. It might be a plugin on the server you're on, but that's just a guess.
