### ISSUE TITLE
Configuration in mod menu

### ISSUE THREAD

**Issue by Birkirrr** [811Alex/NotifMod#8]
The configuration in the mod settings doesn't show, so I'm unable to specify what chat messages gives me notifications.
I have posted a screenshot of the NotifMod in the mod settings below so that you can see.
https://imgur.com/a/jBG1kCu

**Comment by 811Alex** [comment]
Can't reproduce. What Minecraft, Mod Menu, Cloth Config API & Fabric API versions are you using?

**Comment by Birkirrr** [comment]
Minecraft launcher
Fabric-loader-0.14.9-1.19.2
Mod Menu v4.0.6 for 1.19.2
cloth-config-8.2.88-fabric
fabric-api-0.60.0+1.19.2

**Comment by 811Alex** [comment]
Seems to be an issue with newer versions of Cloth Config API, they probably changed something.
Thanks for reporting it! I'll try to fix it soon.

**Comment by Birkirrr** [comment]
Thank you!
