### ISSUE TITLE
Inconsistent crash

### ISSUE THREAD

**Issue by spaghettube** [811Alex/NotifMod#9]
Hey there! I've been experiencing a crash ever so often, I asked a mod dev friend and he told me it had something to do with the sound engine. All of the mods that change sounds on my client would be extra sounds, presence footsteps and notif mod. I couldnt and still cant replicate the crash consistenly so I opted to try and remove one of the mods and see if the crash stops occurring. I've come here to report that it has stopped for a very long time after removing your mod. As I said, this crash is inconsistent, therefore I do not know if it is a mod incompatibility or only your mod's fault or even if it is related to your mod at all.

I'll also be sending the crash report:
[crash-2022-09-15_19.27.30-client.txt](https://github.com/811Alex/NotifMod/files/9740507/crash-2022-09-15_19.27.30-client.txt)

**Comment by 811Alex** [comment]
Hi, thanks for reporting this!

>  I opted to try and remove one of the mods and see if the crash stops occurring

Did you by any chance also try removing either "extra sounds" or "presence footsteps" to see if it stops?
No worries if not, just seeing if I can save some time figuring this one out, when I can give it a go.

**Comment by spaghettube** [comment]
Well, as I said this is an inconsistent crash and I wasnt fully content on reporting this with only removing notifmod but I did it anyways. I have not tried testing the mod incompatibility possibility by removing one of those mods, I'll do it and come report back, though it can take a big while.

**Comment by 811Alex** [comment]
Alright, no problem either way, I'll look at it when I have some time c:

**Comment by spaghettube** [comment]
Hey there, I've come back with some info. So here's what I concluded: extrasounds+notifmod+presencefootsteps=crash; notifmod+presencefootsteps=no crash; extrasounds+presencefootsteps=no crash. I'm guessing that presencefootsteps can be ruled out so it's an incompatibility with extrasounds (?). Hope this helps!

**Comment by spaghettube** [comment]
Actually, exactly as I sent this new comment the crash appeared again, this time with notifmod+presencefootsteps. I dont know with which other mod this could be interfering with ?-?
[crash-2022-10-15_23.02.56-client.txt](https://github.com/811Alex/NotifMod/files/9793205/crash-2022-10-15_23.02.56-client.txt)

**Comment by 811Alex** [comment]
Alright, thanks for testing those out! I don't think it's a _specific_ mod that it's incompatible with tbh, but yeah, this is probably enough info to help figure it out when I can get to it.

**Comment by 811Alex** [comment]
Hopefully this will do it, but it's kinda hard for me to test this one.
Definitely let me know if this is still an issue (please verify crashes are still related to NotifMod - perhaps by checking if they still happen without it - and let me know if your errors in the logs are any different).
